---
sources:
  go: true
allowed:
  - mit
  - apache-2.0
  - mpl-2.0
  - bsd-2-clause
  - bsd-3-clause
  - isc
# add private repos to be ignored here (ex: github.com/my/repo/**/*)
#ignored:
#  go:
reviewed:
  go:
    - gopkg.in/yaml.v3 # apache-2.0
